export const homeFeed = [
  {
    userHandle: "@LA_GAZETTE",
    userImg: "/assets/lag.jpg",
    username: "Los Angeles Gazette",
    timestamp: Math.floor(Math.random() * 24),
    tweetImg: "/assets/jada.jpg",
    commentCount: Math.floor(Math.random() * 200),
    retweetCount: Math.floor(Math.random() * 200),
    likeCount: Math.floor(Math.random() * 11200),
    impressionsCount: Math.floor(Math.random() * 900) + 0.2,
    verified: true,
    tweetMessage:
      "BREAKING: Jada Pinket-Smith reveals she's never met Will Smith, claims we were all hallucinating.",
  },
  {
    userHandle: "@RocketRhubarb",
    userImg: "/assets/dupont.jpg",
    username: "Melissa",
    timestamp: Math.floor(Math.random() * 24),
    tweetImg: "",
    commentCount: Math.floor(Math.random() * 300),
    retweetCount: Math.floor(Math.random() * 50),
    likeCount: Math.floor(Math.random() * 1000),
    impressionsCount: Math.floor(Math.random() * 100) + 0.2,
    verified: false,
    tweetMessage:
      "Find me ONE video cuter than this. Find me just ONE, I'll waaaait!",
    videoLink: "/assets/bearvid.mp4",
  },
  {
    userHandle: "@TechNinjaUnicorn66",
    userImg: "/assets/ron.jpg",
    username: "tim_tech",
    timestamp: Math.floor(Math.random() * 24),
    // tweetImg: "/assets/jada.jpg",
    commentCount: Math.floor(Math.random() * 5),
    retweetCount: Math.floor(Math.random() * 50),
    likeCount: Math.floor(Math.random() * 120),
    impressionsCount: Math.floor(Math.random() * 30) + 0.2,
    verified: false,
    tweetMessage:
      "So Sony be making Spiderman 2 a PS5 exclusive? Bro how??? I live in my momma's basement & got child-support for 8 kids. I cannot afford a PS5, somebody better do the Lord's work!!",
  },
  {
    userHandle: "@sgf_property",
    userImg: "/assets/bear1.jpg",
    username: "sam goldstein-freid - realtor",
    timestamp: Math.floor(Math.random() * 24),
    tweetImg: "/assets/madhome.jpg",
    commentCount: Math.floor(Math.random() * 20),
    retweetCount: Math.floor(Math.random() * 70),
    likeCount: Math.floor(Math.random() * 100),
    impressionsCount: Math.floor(Math.random() * 100) + 0.2,
    verified: true,
    tweetMessage:
      "NEWLY LISTED. Tour this $45,000,000 secluded farm. A stunning, airy 12,000sqft mega haven in Park City, Utah. Peaceful, holds 7bed, 10bath, rugby/soccer pitch & horse stables/barn on 15acres, just an incredible listing. WATCH HOME TOUR: http/realtoresam.com/dj83hwd",
  },
  {
    userHandle: "@drakes_babe",
    userImg: "/assets/follow3.jpg",
    username: "call me queen",
    timestamp: Math.floor(Math.random() * 24),
    tweetImg: "/assets/sleep.jpg",
    commentCount: 23,
    retweetCount: 121,
    likeCount: 123,
    impressionsCount: 112.8,
    verified: false,
    tweetMessage:
      "Tbh we all agree uguthi life is wild ey?! Sleeping the stress away >>>",
  },

  {
    userHandle: "@pixelpirate42",
    userImg: "/assets/hardy.jpg",
    username: "hillip_Pirate",
    timestamp: Math.floor(Math.random() * 24),
    tweetImg: "",
    commentCount: Math.floor(Math.random() * 200),
    retweetCount: Math.floor(Math.random() * 200),
    likeCount: Math.floor(Math.random() * 11200),
    impressionsCount: Math.floor(Math.random() * 300) + 0.5,
    verified: false,
    tweetMessage: "Man City supporters deserve less lololol",
  },
  {
    userHandle: "@CaptainCookiez",
    userImg: "/assets/queen.jpg",
    username: "amandaLinkS",
    timestamp: Math.floor(Math.random() * 24),
    tweetImg: "/assets/voldy.jpg",
    commentCount: Math.floor(Math.random() * 200),
    retweetCount: Math.floor(Math.random() * 200),
    likeCount: Math.floor(Math.random() * 11200),
    impressionsCount: Math.floor(Math.random() * 300) + 0.7,
    verified: true,
    tweetMessage: "Hai ke sana, men are not good people. Yoh!!",
    videoLink: "",
  },

  {
    userHandle: "@mystery__Mango",
    userImg: "/assets/jake.jpg",
    username: "mangodon",
    timestamp: Math.floor(Math.random() * 24),
    tweetImg: "",
    commentCount: Math.floor(Math.random() * 200),
    retweetCount: Math.floor(Math.random() * 200),
    likeCount: Math.floor(Math.random() * 11200),
    impressionsCount: Math.floor(Math.random() * 300) + 0.3,
    verified: false,
    tweetMessage:
      "Money. Bread. Moola. Geld. Machankura. Get money & stay ghost.",
  },
  {
    userHandle: "@pablitoHoffer",
    userImg: "/assets/follow2.jpg",
    username: "Lesego Mafiwa Gossip",
    timestamp: Math.floor(Math.random() * 24),
    tweetImg: "/assets/trump.jpg",
    commentCount: Math.floor(Math.random() * 200),
    retweetCount: Math.floor(Math.random() * 200),
    likeCount: Math.floor(Math.random() * 11200),
    impressionsCount: Math.floor(Math.random() * 300) + 0.3,
    verified: true,
    tweetMessage:
      "HOT TOPIC: TRUMP ADDRESSES ONLYFANS RUMOURS! Link in first comment",
  },
  {
    userHandle: "@genie_xx",
    userImg: "/assets/laurent.jpg",
    username: "supreme goddess",
    timestamp: Math.floor(Math.random() * 24),
    tweetImg: "",
    commentCount: Math.floor(Math.random() * 200),
    retweetCount: Math.floor(Math.random() * 200),
    likeCount: Math.floor(Math.random() * 11200),
    impressionsCount: Math.floor(Math.random() * 300) + 0.3,
    verified: false,
    tweetMessage:
      "Eminem was IN HIS BAG on rap god. IDGAF I said wuh uh said! Nd that's on puuur, chile, or whateva tf yal say",
  },
  {
    userHandle: "@potter_head_dwg",
    userImg: "/assets/dude1.jpg",
    username: "prof snape",
    timestamp: Math.floor(Math.random() * 24),
    tweetImg: "/assets/queen.jpg",
    commentCount: Math.floor(Math.random() * 100),
    retweetCount: Math.floor(Math.random() * 150),
    likeCount: Math.floor(Math.random() * 100),
    impressionsCount: Math.floor(Math.random() * 300) + 0.8,
    verified: false,
    tweetMessage: "Fr fr fr doe!!!!!",
  },
  {
    userHandle: "@sneaky_sasquatch",
    userImg: "/assets/bear1.jpg",
    username: "Sneaky Sasquatch",
    timestamp: Math.floor(Math.random() * 24),
    tweetImg: "/assets/bear1.jpg",
    commentCount: Math.floor(Math.random() * 100),
    retweetCount: Math.floor(Math.random() * 150),
    likeCount: Math.floor(Math.random() * 100),
    impressionsCount: Math.floor(Math.random() * 300) + 0.2,
    verified: true,
    tweetMessage:
      "HORROR OF THE DAY: In 2007, an Alaskan named Lukewold Dwayne Harvey IV adopted a bear cub and nurtured it. After four years of close companionship, the bear unexpectedly stopped eating its regular food and tragically, in a shocking turn of events, the bear fatally injured Mr Harvey. Upon authorities arrival at the scene, they found only a pile of bones as the devastating outcome of this unfortunate incident. Tl;dr: BEARS ARE NOT PETS!",
  },

  {
    userHandle: "@timetravelingtaco",
    userImg: "/assets/bear1.jpg",
    username: "Taco y Tequila",
    timestamp: Math.floor(Math.random() * 24),
    tweetImg: "/assets/drinkjoke.jpg",
    commentCount: Math.floor(Math.random() * 100),
    retweetCount: Math.floor(Math.random() * 150),
    likeCount: Math.floor(Math.random() * 100),
    impressionsCount: Math.floor(Math.random() * 300) + 0.2,
    verified: false,
    tweetMessage: "",
  },
  {
    userHandle: "@E_BikeCo",
    userImg: "/assets/bear1.jpg",
    username: "The E-Bike Co.",
    timestamp: Math.floor(Math.random() * 24),
    tweetImg: "",
    commentCount: Math.floor(Math.random() * 100),
    retweetCount: Math.floor(Math.random() * 150),
    likeCount: Math.floor(Math.random() * 100),
    impressionsCount: Math.floor(Math.random() * 300) + 0.2,
    verified: true,
    tweetMessage:
      "THE FUTURE IS NOW. Introducing the X-Pro Lite MegaTing X3 Book a test here: http://ebikeco/modelx34pro/dnje90/test",
    videoLink: "/assets/bikevid.mp4",
  },
  {
    userHandle: "@flyhalf_vyfxx",
    userImg: "/assets/bear1.jpg",
    username: "Handre v.d Vyfer",
    timestamp: Math.floor(Math.random() * 24),
    tweetImg: "",
    commentCount: Math.floor(Math.random() * 100),
    retweetCount: Math.floor(Math.random() * 150),
    likeCount: Math.floor(Math.random() * 100),
    impressionsCount: Math.floor(Math.random() * 300) + 0.2,
    verified: true,
    tweetMessage: "What a game. Common Faf W hehe. Kolbe was solid too",
    videoLink: "",
  },
];

/*    "@MoonwalkMagician",

    "@JazzCatWhisperer",
    "",
    "@CyberPineapple",
    "@GalacticGiraffe",
    "@DiscoDinosaur77",
    
    "@RetroRainbowZebra",
    "@AstroAvocado",
    "@SteampunkSquirrel",
    "@CryptoCactus",
    "@GamerGoblin",
    "@NeonNarwhal23",
    "@SpicySphinx",
    "@JungleJellybean",
    "@WizardlyWalrus",
    "@SynthWaveStarfish",
    "@MysticalMuffinMan",
    "@FlannelFlamingo",
    "@WhimsicalWombat",
    "@AquaAstronaut",


console.log(fakeTwitterHandles);


*/
