export const listData = [
  {
    img: "/assets/baecation.jpg",
    title: "Baecations",
    memberCount: Math.floor(Math.random() * 9000),
    followerCount: Math.floor(Math.random() * 100000),
    includingWho: "@nicki_minaj",
    includingWho2: "and @puffy",
  },
  {
    img: "/assets/neon1.jpg",
    title: "World RnB",
    memberCount: Math.floor(Math.random() * 400),
    followerCount: Math.floor(Math.random() * 800),
    includingWho: "@btn_news",
  },
  {
    img: "/assets/gta6.jpg",
    title: "GTA VI",
    memberCount: Math.floor(Math.random() * 7000),
    followerCount: Math.floor(Math.random() * 10000),
    includingWho: "@rockstar_ games",
    includingWho2: "and @naughty_dog",
  },
  {
    img: "/assets/dupont.jpg",
    title: "Mzanzi Baddieeeez",
    memberCount: Math.floor(Math.random() * 200),
    followerCount: Math.floor(Math.random() * 4100),
    includingWho: "@jeffbezos",
    includingWho2: "and @princeharry",
  },
  {
    img: "/assets/lewis1.jpg",
    title: "GOATMilton fans",
    memberCount: Math.floor(Math.random() * 200),
    followerCount: Math.floor(Math.random() * 4100),
    includingWho: "@maxverstappen33,",
    includingWho2: "@christian_horner and @redbullracing",
  },
  {
    img: "/assets/brent.jpg",
    title: "Brent Music",
    memberCount: Math.floor(Math.random() * 30000),
    followerCount: Math.floor(Math.random() * 124100),
    includingWho: "@kehlani",
  },
  {
    img: "/assets/mercf1.jpg",
    title: "Merc F1 Club",
    memberCount: Math.floor(Math.random() * 200),
    followerCount: Math.floor(Math.random() * 4100),
    includingWho: "@lewis_44_hamilton",
    includingWho2: "and @daniel_ricciardo3",
  },
  {
    img: "/assets/ghadzi.jpg",
    title: "Dubai Monieees",
    memberCount: Math.floor(Math.random() * 200),
    followerCount: Math.floor(Math.random() * 4100),
    includingWho: "@imanghadzi",
  },
];
