import { trendingTweetCard, trendingTweetCardType } from "@/myTypes";

/*

[{
	"resource": "/c:/Users/mocma/Documents/code/portfolio/projects/twitterclone/app/myData/moreTrendingdata.ts",
	"owner": "typescript",
	"code": "2740",
	"severity": 8,
	"message": "Type '{ userHandle: string; userImg: string; username: string; timestamp: number; tweetImg: string; commentCount: number; retweetCount: number; likeCount: number; impressionsCount: number; verified: boolean; tweetMessage: string; }[]' is missing the following properties from type 'trendingTweetCardType': userImg, username, userHandle, timestamp, and 5 more.",
	"source": "ts",
	"startLineNumber": 3,
	"startColumn": 14,
	"endLineNumber": 3,
	"endColumn": 30
}]

*/

export const moreTrendingData: trendingTweetCardType[] = [
  //   {
  //     userHandle: "@pixelpirate42",
  //     userImg: "/assets/voldy.jpg",
  //     username: "hillip_Pirate",
  //     timestamp: 18,
  //     tweetImg: "",
  //     commentCount: Math.floor(Math.random() * 200),
  //     retweetCount: Math.floor(Math.random() * 200),
  //     likeCount: Math.floor(Math.random() * 11200),
  //     impressionsCount: Math.floor(Math.random() * 300) + 0.5,
  //     verified: true,
  //     tweetMessage: "Man City supporters deserve less lololol",
  //   },
  {
    userImg: "/assets/flatline.jpg",
    username: "FLATLINE NEWS",
    userHandle: "@flat_line",
    timestamp: Math.floor(Math.random() * 17),
    tweetImg: "/assets/ye1.jpg",
    commentCount: Math.floor(Math.random() * 200),
    retweetCount: Math.floor(Math.random() * 200),
    likeCount: Math.floor(Math.random() * 11200),
    impressionsCount: Math.floor(Math.random() * 300) + 0.5,
    verified: true,
    tweetMessage:
      "HOT NEWS: Kanye West reveals name change: NOW CALLED 'Kanye East'",
    videoLink: "",
  },
  {
    userImg: "/assets/neon1.jpg",
    username: "neonite bubblezzz",
    userHandle: "@neon__bbzz",
    timestamp: Math.floor(Math.random() * 17),
    commentCount: Math.floor(Math.random() * 200),
    retweetCount: Math.floor(Math.random() * 200),
    likeCount: Math.floor(Math.random() * 11200),
    impressionsCount: Math.floor(Math.random() * 300) + 0.7,
    verified: true,
    tweetMessage:
      "I am a GRAMMY NOMINEE! i swear when i get rich-rich yal wont kno 4 sho bt the signs will b there lmfao lololol. anyway click my bio for new track released yesterday!!",
  },
  {
    userImg: "/assets/minaj.jpg",
    username: "Nicki Minaj",
    userHandle: "@onika",
    timestamp: Math.floor(Math.random() * 2),
    tweetImg: "/assets/minaj.jpg",
    commentCount: Math.floor(Math.random() * 60000),
    retweetCount: Math.floor(Math.random() * 90200),
    likeCount: Math.floor(Math.random() * 1010200),
    impressionsCount: Math.floor(Math.random() * 300) + 0.1,
    verified: true,
    tweetMessage:
      "Calling all my Barbzz. I LOVE yal. Yal like 1000x better than Beyonce's fans. Them beehive brats. Nah fr fr I luv yaaaal!",
  },
  {
    userImg: "/assets/news2.jpg",
    username: "The Digest",
    userHandle: "thee_die_jest",
    timestamp: Math.floor(Math.random() * 17),
    tweetImg: "/assets/kimk2.jpg",
    commentCount: Math.floor(Math.random() * 200),
    retweetCount: Math.floor(Math.random() * 200),
    likeCount: Math.floor(Math.random() * 11200),
    impressionsCount: Math.floor(Math.random() * 300) + 0.8,
    verified: true,
    tweetMessage:
      "Kim K WOWS in stunning, $3million Thiery du Levesque gown. Credits ex Pete Davidson for being 'supportive friend' amidst tax allegations",
  },
  {
    userImg: "/assets/hardy.jpg",
    username: "Tom Hardy",
    userHandle: "tom_hardy",
    timestamp: Math.floor(Math.random() * 17),
    tweetImg: "/assets/bane.jpg",
    commentCount: Math.floor(Math.random() * 300),
    retweetCount: Math.floor(Math.random() * 20000),
    likeCount: Math.floor(Math.random() * 411200),
    impressionsCount: Math.floor(Math.random() * 300) + 0.3,
    verified: true,
    tweetMessage:
      "I had a lot of fun on this. Bane was really challenging to play.",
    videoLink: "",
  },
  {
    userImg: "/assets/sleep.jpg",
    username: "Bass tv",
    userHandle: "@bass__tv",
    timestamp: Math.floor(Math.random() * 17),
    tweetImg: "/assets/uzi1.jpg",
    commentCount: Math.floor(Math.random() * 200),
    retweetCount: Math.floor(Math.random() * 200),
    likeCount: Math.floor(Math.random() * 11200),
    impressionsCount: Math.floor(Math.random() * 300) + 0.5,
    verified: true,
    tweetMessage: "Lil Uzi Vert announces 100 SHOW tour in Uganda",
    videoLink: "",
  },
  {
    userImg: "/assets/britney.jpg",
    username: "Britney Spears",
    userHandle: "@its_britney_biish",
    timestamp: Math.floor(Math.random() * 17),
    tweetImg: "",
    commentCount: Math.floor(Math.random() * 200),
    retweetCount: Math.floor(Math.random() * 200),
    likeCount: Math.floor(Math.random() * 11200),
    impressionsCount: Math.floor(Math.random() * 300) + 0.5,
    verified: true,
    tweetMessage:
      "A million likes and I'm dropping a teaser for my new album! So excited!!",
    videoLink: "",
  },
  {
    userImg: "/assets/britney.jpg",
    username: "Britney Spears",
    userHandle: "@its_britney_biish",
    timestamp: Math.floor(Math.random() * 17),
    tweetImg: "/assets/britneyalbum.png",
    commentCount: Math.floor(Math.random() * 200),
    retweetCount: Math.floor(Math.random() * 200),
    likeCount: Math.floor(Math.random() * 11200),
    impressionsCount: Math.floor(Math.random() * 300) + 0.5,
    verified: true,
    tweetMessage:
      "My new EP will be a revisit of 'In The Zone'. I literally CAN'T WAIT to show you guys my baaaaabeyyy!!! ",
    videoLink: "",
  },
  {
    userImg: "/assets/ariana.jpg",
    username: "Ariana Grande",
    userHandle: "@ari_g_butera",
    timestamp: Math.floor(Math.random() * 17),
    tweetImg: "",
    commentCount: Math.floor(Math.random() * 200),
    retweetCount: Math.floor(Math.random() * 200),
    likeCount: Math.floor(Math.random() * 11200),
    impressionsCount: Math.floor(Math.random() * 300) + 0.5,
    verified: true,
    tweetMessage: "I miss Pete. Don't judge me luvs.",
    videoLink: "",
  },
];
